#
# Books (that I've read and recommend)
# -- Ordered by name
#
books = [
  { title = "10% Happier", author = "Dan Harris" },
  { title = "Benjamin Franklin", author = "Walter Isaacson" },
  { title = "Bigger Leaner Stronger", author = "Michael Matthews" },
  { title = "Daily Rituals: How Artists Work", author = "Mason Currey" },
  { title = "Getting Real", author = "37 Signals" },
  { title = "How We Got to Now", author = "Steven Johnon" },
  { title = "Making Ideas Happen", author = "Scott Belsky" },
  { title = "Meditations", author = "Marcus Aurelius", reading = true },
  { title = "Rework", author = "Jason Fried" },
  { title = "So Good They Can't Ignore You", author = "Cal Newport" },
  { title = "Tesla: Man Out of Time", author = "Margaret Cheney" },
  { title = "The 4-Hour Workweek", author = "Timothy Ferriss", reading = true },
  { title = "The 4-Hour Body", author = "Timothy Ferriss" },
  { title = "The Art of Learning", author = "Josh Waitzkin" },
  { title = "The Icarus Deception", author = "Seth Godin" },
  { title = "The Information", author = "James Gleick" },
  { title = "The Obstacle Is the Way", author = "Ryan Holiday" },
  { title = "The Wild Diet", author = "Abel James" },
  { title = "Vagabonding", author = "Rolf Potts" },
  { title = "We Learn Nothing", author = "Tim Kreider" },
  { title = "You're Never Weird on the Internet (Almost)", author = "Felicia Day" },
  { title = "Zen and the Art of Motorcycle Maintenance", author = "Robert Pirsig" },
]


books__toread = [
  { title = "Cat's Cradle", author = "Kurt Vonnegut" },
  { title = "The Alchemist", author = "Paulo Coelho" },
]


books__average = [
  { title = "One, Two, Three: Absolutely Elementary Mathematics", author = "David Berlinkski" },
  { title = "Journey to the Center of the Earth", author = "Jules Verne" },
  { title = "Pythagoras & His Theorem", author = "Paul Strathern" },
  { title = "Wizard: The Life and Times of Nikola Tesla", author = "Marc Seifer" },
]


#
# Projects
# -- Ordered by name
#
[[projects]]
name = "Ectograph"
url = "https://github.com/icidasset/ectograph"
description = "A set of utility functions for using Ecto in combination with GraphQL (joshprice/graphql-elixir)."
promote = true

[[projects]]
name = "Electricity & Mathematics"
url = "https://electrical-mathematics.surge.sh/"
description = "All you need to learn about electrical engineering from the ground up."
promote = true

[[projects]]
name = "Key Maps"
url = "https://github.com/icidasset/key-maps"
description = "Provides an interface to fill in custom data structures and a JSON api with CORS support to fetch the data."

[[projects]]
name = "Ongaku Ryoho"
url = "https://github.com/icidasset/ongaku-ryoho"
description = "A music player which connects to your cloud storage."
promote = true

[[projects]]
name = "Static Base"
url = "https://github.com/icidasset/static-base"
description = "A small functional toolset for building static websites."
promote = true

[[projects]]
name = "Static Base Contrib"
url = "https://github.com/icidasset/static-base-contrib"
description = "Functions you can use with static-base."
