#
# Projects
# -- Ordered by name
#
[[projects]]
name = "Ectograph"
url = "https://github.com/icidasset/ectograph"
promote = true

[[projects]]
name = "Electricity & Mathematics"
url = "https://electrical-mathematics.surge.sh/"
promote = true

[[projects]]
name = "Key Maps"
url = "https://github.com/icidasset/key-maps"

[[projects]]
name = "Ongaku Ryoho"
url = "https://github.com/icidasset/ongaku-ryoho"
promote = true

[[projects]]
name = "Static Base"
url = "https://github.com/icidasset/static-base"
promote = true

[[projects]]
name = "Static Base Contrib"
url = "https://github.com/icidasset/static-base-contrib"
